---
title: "Turing_Pattern"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(magick)
library(magrittr)
library(ggplot2)
library(dplyr)
```

# Reaction-diffusion system

## Gray-Scott model

```{r include=FALSE}
## Display the grid
save <- function(mat, path, iter){
  png(paste0(path,sprintf("%05d",iter), ".png", collapse = ""))
  par(mar = c(1,1,2,1), pty = "m") 
  image(t(apply(mat,2,rev)), col=hcl.colors(100), yaxt="n", xaxt="n")
  grid(nx = ncol(mat), ny = nrow(mat),col="grey70", lty=1)
  dev.off()
}
```

```{r include=FALSE}
## Display the grid
display <- function(mat, name= " "){
  par(pty = "s") 
  image(t(apply(mat,2,rev)), col=hcl.colors(100), yaxt="n", xaxt="n")
  grid(nx = ncol(mat), ny = nrow(mat),col="grey70", lty=1)
  title(main = paste0(name, collapse = ""))

}
```


```{r include=FALSE}
init <- function(size = 3){
a <- array(1,size**2)
b <- integer(size**2)
m <- array(c(a,b), dim = c(size,size,2))
dimnames(m)[[3]] = c("A", "B")
m[(size/2 - 4):(size/2 + 6), (size/2 - 4):(size/2 + 6), 2] = 1
# m[(size/3 - 2):(size/3 + 2), (size/3 - 2):(size/3 + 2), 2] = 1
# m[(size/4 - 2):(size/4 + 2), (size/4 - 2):(size/4 + 2), 2] = 1
return(m)
}
```

## Laplacian fucntions (convolution)

```{r}
lapA <- function(m,i,j, cw = -1, an = 0.2, dn = 0.05){
  m = m[,,1]
  N = i - 1
  S = i + 1
  W = j - 1
  E = j + 1
  ## For edges
  if (N == 0) {N = 1}
  if (S == dim(m)[1] + 1) {S = dim(m)[1]}
  if (W == 0) {W = 1} 
  if (E == dim(m)[2] + 1) {E = dim(m)[2]}
  sum = m[i,j]*cw + an*(m[N,j]+m[S,j]+m[i,W]+m[i,E]) + dn*(m[N,W]+m[N,E]+m[S,W]+m[S,E])
  return(sum)
}

lapB <- function(m,i,j, cw = -1, an = 0.2, dn = 0.05){
  m = m[,,2]
  N = i - 1
  S = i + 1
  W = j - 1
  E = j + 1
  ## For edges
  if (N == 0) {N = 1}
  if (S == dim(m)[1] + 1) {S = dim(m)[1]}
  if (W == 0) {W = 1} 
  if (E == dim(m)[2] + 1) {E = dim(m)[2]}
  sum = m[i,j]*cw + an*(m[N,j]+m[S,j]+m[i,W]+m[i,E]) + dn*(m[N,W]+m[N,E]+m[S,W]+m[S,E])
  return(sum)
}
```


```{r}
## GSM model

GSM <- function(m,iter, path, dA = 1.1, dB = 0.3, r = 0.95, f = .055, k = 0.062){
  for (a in 1:iter){
  tmp_m = array(0, dim = c(dim(m)[1], dim(m)[2], dim(m)[3]))
    for (i in 1:dim(m)[1]){
      for (j in 1:dim(m)[2]){
        A = m[i,j,1]
        B = m[i,j,2]
        A = A + (dA*lapA(m,i,j) - r*A*B*B + f*(1-A))
        B = B + (dB*lapB(m,i,j) + r*A*B*B - (k+f)*B)
        tmp_m[i,j,1] = A
        tmp_m[i,j,2] = B
      }
    }
  m = tmp_m
  save(m[,,1]-m[,,2],path,a)
  print(a)
  }
  # display(m[,,1]-m[,,2])
}

```


```{r eval=FALSE, include=FALSE}
m <- init(41)
GSM(m,4000,"/Volumes/MyBook_3/git/random-spontaneous-projects/Turing_Pattern_files/default40/")
```

```{r eval=FALSE, include=FALSE}
## This block is used to make gifs, not shown

make_gif <- function(path, gif_name){
list.files(path = path, pattern = "*.png", full.names = T) %>%
  image_read() %>%
  image_join() %>%
  image_animate(fps=20) %>%
  image_write(paste0(path,"/",gif_name,".gif", collapse = ""))
}

make_gif("/Volumes/MyBook_3/git/random-spontaneous-projects/Turing_Pattern_files/default30/gif/", "default")
```






